### ISSUE TITLE
[LAS/LAZ vaults:] LAZ not able to read precision for column Z.

### ISSUE THREAD

**Issue by romulogoncalves** [MonetDBSolutions/data-vaults#13]
lasinfo C_14FN1.LAZ

gives:
 Dimensions
---------------------------------------------------------
  'X'                            --  size: 32 offset: 0
  'Y'                            --  size: 32 offset: 4
  'Z'                            --  size: 32 offset: 8
  'Intensity'                    --  size: 16 offset: 12
  'Return Number'                --  size: 3 offset: 14
  'Number of Returns'            --  size: 3 offset: 14
  'Scan Direction'               --  size: 1 offset: 14
  'Flightline Edge'              --  size: 1 offset: 14
  'Classification'               --  size: 8 offset: 15
  'Scan Angle Rank'              --  size: 8 offset: 16
  'User Data'                    --  size: 8 offset: 17
  'Point Source ID'              --  size: 16 offset: 18
  'Time'                         --  size: 64 offset: 20

However, during loading we get:
goncalve@budapest:Tests$ mclient debug sql < load.sql 
MAPI  = monetdb@localhost:55001
QUERY = --call lidarload('C_14FN1');
        call lidarload('c_14fn1');
        --call lidarload('test2');
ERROR = !Unknown precision for Z column (5)

**Comment by kutsurak** [comment]
This should be fixed in the latest commits in data-vaults branch.
