### ISSUE TITLE
[LAS/LAZ vaults:] The attach must have the parse string.

### ISSUE THREAD

**Issue by romulogoncalves** [MonetDBSolutions/data-vaults#14]
The parse string is used to create the table and later on to parse the file when loading.
At the moment we only load X, Y, Z.

**Comment by kutsurak** [comment]
The parse string is implemented.

The supported entries are:
       x, X - x coordinate as decimal(<num_digits_unscaled_max_x>,<num_digits_scale_x>)
       y, Y - y coordinate as decimal(<num_digits_unscaled_max_y>,<num_digits_scale_y>)
       z, Z - z coordinate as decimal(<num_digits_unscaled_max_z>,<num_digits_scale_z>)
       a - scan angle as tinyint
       i - intensity as smallint
       n - number of returns for given pulse as smallint
       r - number of this return as smallint
       c - classification number as tinyint
       u - user data as tinyint
       p - point source ID as smallint
       e - edge of flight line as smallint
       d - direction of scan flag as smallint
       R - red channel of RGB color as smallint
       G - green channel of RGB color as smallint
       B - blue channel of RGB color as smallint
       M - vertex index number as integer

**Comment by kutsurak** [comment]
lidarattach can be called in three different ways:

lidarattach(<file name/directory name>)
lidarattach(<file name/directory name>, <table name>)
lidarattach(<file name/directory name>, <table name>, <parse string>)

In the first two cases columns x,y and z will be loaded. In the third case, in addition to x, y and z the columns specified by the parse string will also be loaded.
