### ISSUE TITLE
Attach is not able to complete the dir path.

### ISSUE THREAD

**Issue by romulogoncalves** [MonetDBSolutions/data-vaults#16]
For example:
call lidarattach('/scratch/goncalve/data/geo_data/ahn3/tileslaz/tests1');
leads to:
ERROR = !File /scratch/goncalve/data/geo_data/ahn3/tileslaz/tests1C_11FN2.LAZ not found.

It needs to be done like this:
call lidarattach('/scratch/goncalve/data/geo_data/ahn3/tileslaz/tests1/');

**Comment by kutsurak** [comment]
This bug is related to #18, they will both be fixed in the next commit.

**Comment by kutsurak** [comment]
Fixed in b5c080c41cdf
